spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-174.railway.app:5526/railway
    username: postgres
    password: 3R2S9wquI76N9zQ5UxNo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
