spring:
  datasource:
    url: jdbc:postgresql://${RAILWAY_DB_HOST:containers-us-west-174.railway.app}:${RAILWAY_DB_PORT:5526}/${RAILWAY_DB_NAME:railway}
    username: ${RAILWAY_DB_USERNAME:postgres}
    password: ${RAILWAY_DB_PASSWORD:3R2S9wquI76N9zQ5UxNo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
